- name: pack Contoso_University_Core

on:
  Push:
    paths:
      -  contents/**
  workflow_dispatch:

jobs:
  build:
    run-on: ubuntu-latest
      steps:
        uses: actions/checkout@v2

      
