name: pack Contoso_University_Core

on:
  Push:
    paths:
      -  contents/**
  workflow_dispatch:

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions@v1.2.0
        with:
          solution-files: out/contoso_university_core.zip
          solution-folder: contents
          solution-type: Both
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: packaged-solution
          path: out/
